In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
from pandas import json_normalize
import seaborn as sns
import ast

In [3]:
# Se crea una funcion para cargar archivos JSON
def load_json_lines(file_path):

    data = []
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            data.append(ast.literal_eval(line))
    return pd.DataFrame(data)

In [4]:
# Cargar el archivo JSON
df_items = load_json_lines(r'C:\Users\Renato\Desktop\MLOPS_KRAMER\PI MLOps - STEAM\australian_users_items.json')

# Mostrar el DF
df_items

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[]

In [5]:
# Da una informacion sobre el DataFrame creado
print(df_items.info)

# InformaciÃ³n estadÃ­stica de las columnas en el DataFrame
df_items.describe()

<bound method DataFrame.info of                        user_id  items_count           steam_id  \
0            76561197970982479          277  76561197970982479
1                      js41637          888  76561198035864385
2                    evcentric          137  76561198007712555
3                   Riot-Punch          328  76561197963445855
4                        doctr          541  76561198002099482
...                        ...          ...                ...
88305        76561198323066619           22  76561198323066619
88306        76561198326700687          177  76561198326700687
88307  XxLaughingJackClown77xX            0  76561198328759259
88308        76561198329548331            7  76561198329548331
88309        edward_tremethick            0  76561198331598578

                                                user_url  \
0      http://steamcommunity.com/profiles/76561197970...
1                   http://steamcommunity.com/id/js41637
2                 http://steamcommunity.com/id/evcentric
3                http://steamcommunity.com/id/Riot-Punch
4                     http://steamcommunity.com/id/doctr
...                                                  ...
88305  http://steamcommunity.com/profiles/76561198323...
88306  http://steamcommunity.com/profiles/76561198326...
88307  http://steamcommunity.com/id/XxLaughingJackClo...
88308  http://steamcommunity.com/profiles/76561198329...
88309     http://steamcommunity.com/id/edward_tremethick

                                                   items
0      [{'item_id': '10', 'item_name': 'Counter-Strik...
1      [{'item_id': '10', 'item_name': 'Counter-Strik...
2      [{'item_id': '1200', 'item_name': 'Red Orchest...
3      [{'item_id': '10', 'item_name': 'Counter-Strik...
4      [{'item_id': '300', 'item_name': 'Day of Defea...
...                                                  ...
88305  [{'item_id': '413850', 'item_name': 'CS:GO Pla...
88306  [{'item_id': '11020', 'item_name': 'TrackMania...
88307                                                 []
88308  [{'item_id': '304930', 'item_name': 'Unturned'...
88309                                                 []

[88310 rows x 5 columns]>

        items_count
count  88310.000000
mean      58.353629
std      122.312095
min        0.000000
25%        3.000000
50%       26.000000
75%       73.000000
max     7762.000000

In [6]:
# VerificaciÃ³n de datos nulos
print((df_items.isnull().mean() * 100).round(2))

user_id        0.0
items_count    0.0
steam_id       0.0
user_url       0.0
items          0.0
dtype: float64

In [7]:
# Lista que almacena los DataFrames normalizados
lista_df = []

# Itera sobre las filas de la columna 'items'
for index, fila in df_items['items'].items():

    # Normaliza la fila actual y agrega el DataFrame resultante a la lista
    df_normalizado = pd.json_normalize(fila)
    lista_df.append(df_normalizado)

In [8]:
# Concatena los DataFrames normalizados en uno
data_items = pd.concat(lista_df, ignore_index=True)

# Muestra el DF
data_items

,item_id,item_name,playtime_forever,playtime_2weeks
0,10,Counter-Strike,6,0
1,20,Team Fortress Classic,0,0
2,30,Day of Defeat,7,0
3,40,Deathmatch Classic,0,0
4,50,Half-Life: Opposing Force,0,0
...,...,...,...,...
5153204,346330,BrainBread 2,0,0
5153205,373330,All Is Dust,0,0
5153206,388490,One Way To Die: Steam Edition,3,3
5153207,521570,You Have 10 Seconds 2,4,4
5153208,519140,Minds Eyes,3,3

In [9]:
# Elimina la columna items anidada del DataFrame
df_items.drop(columns=['items'], inplace=True)

# Concatena el DataFrame original con la versiÃ³n aplanada de la columna items
df_items_normalizado = pd.concat([df_items, data_items], axis=1)

# Muestra el DataFrame
df_items_normalizado

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277.0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,6,0
1,js41637,888.0,76561198035864385,http://steamcommunity.com/id/js41637,20,Team Fortress Classic,0,0
2,evcentric,137.0,76561198007712555,http://steamcommunity.com/id/evcentric,30,Day of Defeat,7,0
3,Riot-Punch,328.0,76561197963445855,http://steamcommunity.com/id/Riot-Punch,40,Deathmatch Classic,0,0
4,doctr,541.0,76561198002099482,http://steamcommunity.com/id/doctr,50,Half-Life: Opposing Force,0,0
...,...,...,...,...,...,...,...,...
5153204,NaN,NaN,NaN,NaN,346330,BrainBread 2,0,0
5153205,NaN,NaN,NaN,NaN,373330,All Is Dust,0,0
5153206,NaN,NaN,NaN,NaN,388490,One Way To Die: Steam Edition,3,3
5153207,NaN,NaN,NaN,NaN,521570,You Have 10 Seconds 2,4,4
5153208,NaN,NaN,NaN,NaN,519140,Minds Eyes,3,3

In [10]:
# Chequeo de valores NaN por columna
cantidad_NaN = df_items_normalizado.isna().sum()

print(cantidad_NaN)

# Porcentaje de datos nulos por columna
porcentaje_nulos = (df_items_normalizado.isnull().mean() * 100).round(2)

print('\n', porcentaje_nulos)

df_user_items = df_items_normalizado

user_id             5064899
items_count         5064899
steam_id            5064899
user_url            5064899
item_id                   0
item_name                 0
playtime_forever          0
playtime_2weeks           0
dtype: int64

 user_id             98.29
items_count         98.29
steam_id            98.29
user_url            98.29
item_id              0.00
item_name            0.00
playtime_forever     0.00
playtime_2weeks      0.00
dtype: float64

In [11]:
# Eliminar los datos nulos
df_user_items = df_user_items.dropna()

df_user_items

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277.0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,6,0
1,js41637,888.0,76561198035864385,http://steamcommunity.com/id/js41637,20,Team Fortress Classic,0,0
2,evcentric,137.0,76561198007712555,http://steamcommunity.com/id/evcentric,30,Day of Defeat,7,0
3,Riot-Punch,328.0,76561197963445855,http://steamcommunity.com/id/Riot-Punch,40,Deathmatch Classic,0,0
4,doctr,541.0,76561198002099482,http://steamcommunity.com/id/doctr,50,Half-Life: Opposing Force,0,0
...,...,...,...,...,...,...,...,...
88305,76561198323066619,22.0,76561198323066619,http://steamcommunity.com/profiles/76561198323...,273350,Evolve Stage 2,23,0
88306,76561198326700687,177.0,76561198326700687,http://steamcommunity.com/profiles/76561198326...,10,Counter-Strike,48,0
88307,XxLaughingJackClown77xX,0.0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,80,Counter-Strike: Condition Zero,0,0
88308,76561198329548331,7.0,76561198329548331,http://steamcommunity.com/profiles/76561198329...,100,Counter-Strike: Condition Zero Deleted Scenes,0,0
88309,edward_tremethick,0.0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,240,Counter-Strike: Source,213,0

In [13]:
# Exporto los DataFrame en formato CSV, JSON y Parquet

df_user_items.to_csv('df_user_items.csv', index=False)

df_user_items.to_json('df_user_items.json', orient='records', lines=True)

df_user_items.to_parquet('df_user_items.parquet', index=False)